/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report deterministic processor and demo-dataset readiness */
        get: operations["get_health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DatasetSummary */
        DatasetSummary: {
            /** Frame Count */
            frame_count: number;
            /** Height */
            height: number;
            /** Id */
            id: string;
            /** Total Bytes */
            total_bytes: number;
            /** Width */
            width: number;
        };
        /** HealthResponse */
        HealthResponse: {
            dataset?: components["schemas"]["DatasetSummary"] | null;
            /** Limitations */
            limitations: string[];
            /** Python Version */
            python_version: string;
            /**
             * Service
             * @default photofold-processor
             * @constant
             */
            service: "photofold-processor";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Webp Available */
            webp_available: boolean;
            /** Webp Roundtrip */
            webp_roundtrip: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
